name: iherd2
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  file_picker: ^4.0.0
  path_provider: ^2.0.2 
  shared_preferences: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  charts_flutter: ^0.10.0
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4
  fl_chart: ^0.40.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/farmer.png"


  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/client1.png
    - assets/client2.png
    - assets/client3.png





 
  uses-material-design: true
